---
title: "p8105_hw5_nk2814"
author: "Naama Kipperman"
date: "11/5/2019"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(rvest)
library(readr)
library(patchwork)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)


```

#### Problem 1 


```{r}

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) 


# Write function that replaces missing values accordingly 

replace_missing_vals = function(x){
  if (is.numeric(x))
  {x = replace_na(x, mean(x, na.rm=TRUE))}
  else if (is.character(x))
  {x = replace_na(x, "virginica")}
}


fixed_iris = map(iris_with_missing, replace_missing_vals) %>% 
  as_tibble()

```


#### Problem 2 


```{r}
p2_files = list.files(path="./hw5_data/data", full.names=TRUE)
  
trial_data =
  p2_files %>% 
map_df(read.csv) %>%
  mutate(
    subj_id = c(1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10),
    study_arm = c("control", "control", "control", "control", "control", "control", "control", "control", "control", "control", "experimental", "experimental", "experimental", "experimental", "experimental", "experimental", "experimental", "experimental", "experimental", "experimental")
  ) %>% 
  select(subj_id, study_arm, everything()) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "values"
  ) 

trial_data %>% 
  ggplot(aes(x=week, y=values, color=subj_id)) + geom_point()+ geom_line(aes(group=subj_id)) + facet_grid(rows=vars(study_arm))



```




